### ISSUE TITLE
Traptor is missing some rule_tag and rule_value matches in nested objects

### ISSUE THREAD

**Issue by jasonrhaas** [istresearch/traptor#36]
Traptor is not iterating through the tweet object properly to search all places where a match can be.

**Comment by jasonrhaas** [comment]
Version 1.1.3 now uses the `flatdict` library to flatten the dictionary first and then iterate through looking for matches.

**Comment by rdempsey** [comment]
Handled in 1.1.3 per Jason's comment above.
