### ISSUE TITLE
Create rule manager daemon for traptor

### ISSUE THREAD

**Issue by jasonrhaas** [istresearch/traptor#5]
Currently the rulesets for `traptor` are parsed out with a script `rule-extract.py` and added to a redis database manually.  Would like to have something running that checks every `x` minutes for new rules, and if there are new rules, push updates out to the traptors with the new rules.

For this, the API connection need to be reset so we don't want to do this too often.

**Comment by jasonrhaas** [comment]
Going to use a redis pub-sub approach for the rule manager.

**Comment by jasonrhaas** [comment]
@rdempsey can you update this issue?  Should be able to close this out with v1.1

**Comment by rdempsey** [comment]
This functionality has been implemented as another project. Traptor will refresh it's rules if it finds a message for itself in the Redis pubsub. Check the docs for all the info!
